# Generated by Django 4.1 on 2022-09-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_story',
            name='historial',
            field=models.TextField(blank=True),
        ),
    ]
