# Generated by Django 4.1 on 2022-09-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0002_tipous_proyecto_descripcion_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='cargahoraria',
            field=models.IntegerField(default=0),
        ),
    ]
