# Generated by Django 4.1 on 2022-10-15 02:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0002_alter_user_story_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
