# Generated by Django 4.1 on 2022-10-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0003_sprint_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='descripcion',
        ),
    ]
