# Generated by Django 4.1 on 2022-09-04 23:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('Proyect_Agile', '0003_alter_miembro_cargahoraria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='miembro',
            name='correo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.emailaddress'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechafin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechainicio',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='scrumMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.emailaddress'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='usbacklog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Proyect_Agile.user_story'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
