# Generated by Django 4.1 on 2022-09-27 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0003_alter_rol_idproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipous',
            name='idproyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Proyect_Agile.proyecto'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='idProyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Proyect_Agile.proyecto'),
        ),
    ]
