# Generated by Django 4.1 on 2022-10-15 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyect_Agile', '0004_remove_sprint_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_story',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_story',
            name='estimacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_story',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_story',
            name='tiempoDedicado',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PlanningPoker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimacionSM', models.FloatField()),
                ('estimacionEncargado', models.FloatField(blank=True, null=True)),
                ('estimacionFinal', models.FloatField(blank=True, null=True)),
                ('prioridad', models.IntegerField()),
                ('estado', models.CharField(choices=[('N', 'Nuevo'), ('PP', 'En Planning Pocker'), ('P', 'Pendiente'), ('EP', 'En Proceso'), ('STSA', 'Sin Terminar Sprint Anterior'), ('A', 'Aprobado'), ('H', 'Hecho'), ('C', 'Cancelado')], default='N', max_length=4)),
                ('idSprint', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Proyect_Agile.sprint')),
                ('idUs', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Proyect_Agile.user_story')),
                ('miembroEncargado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Proyect_Agile.miembro')),
            ],
        ),
    ]
