# Generated by Django 4.1 on 2022-09-27 03:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0004_tipous_idproyecto_alter_rol_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipous',
            name='estado',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PH', 'Por Hacer'), ('EP', 'En Proceso'), ('H', 'Hecho'), ('C', 'Cancelado')], default='N', max_length=4), default=list, size=None),
        ),
    ]
