# Generated by Django 4.1 on 2022-09-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0005_alter_tipous_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipous',
            name='estado',
            field=models.CharField(choices=[('PH', 'Por Hacer'), ('EP', 'En Proceso'), ('H', 'Hecho'), ('C', 'Cancelado')], default='N', max_length=4),
        ),
    ]
