# Generated by Django 4.1 on 2022-09-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0006_alter_tipous_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipous',
            name='estado',
            field=models.TextField(default='Por hacer, En Proceso, Hecho, Cancelado'),
        ),
    ]
