# Generated by Django 4.1 on 2022-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0006_rename_estimacionsm_planningpoker_estimacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningpoker',
            name='estado',
            field=models.CharField(choices=[('N', 'Nuevo'), ('PP', 'En Planning Pocker'), ('P', 'Pendiente'), ('EP', 'En Proceso'), ('STSA', 'Sin Terminar en Sprint Anterior'), ('A', 'Aprobado'), ('H', 'Hecho'), ('C', 'Cancelado')], default='N', max_length=4),
        ),
        migrations.AlterField(
            model_name='planningpoker',
            name='prioridad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
