# Generated by Django 4.1.1 on 2022-09-22 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyect_Agile', '0006_remove_miembro_correo_miembro_idproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
