# Generated by Django 4.1 on 2022-10-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0007_alter_planningpoker_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_story',
            name='encargado',
        ),
    ]
