# Generated by Django 4.1.1 on 2022-09-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0007_alter_tipous_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_story',
            name='idproyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Proyect_Agile.proyecto'),
        ),
    ]
