# Generated by Django 4.1.1 on 2022-09-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0008_user_story_idproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_story',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=30),
        ),
    ]
