# Generated by Django 4.1 on 2022-11-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0009_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PH', 'Por Hacer'), ('H', 'Haciendo'), ('HE', 'Hecho')], default='PH', max_length=4),
        ),
    ]
