# Generated by Django 4.1 on 2022-11-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0011_remove_planningpoker_bv_remove_planningpoker_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_story',
            name='estimacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_story',
            name='idSprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Proyect_Agile.sprint'),
        ),
        migrations.AlterField(
            model_name='user_story',
            name='estado',
            field=models.CharField(choices=[('N', 'Nuevo'), ('PP', 'En Planning Pocker'), ('P', 'Pendiente'), ('EP', 'En Proceso'), ('STSA', 'Sin Terminar en Sprint Anterior'), ('A', 'Aprobado'), ('H', 'Hecho'), ('C', 'Cancelado')], default='N', max_length=30),
        ),
        migrations.DeleteModel(
            name='PlanningPoker',
        ),
    ]
