# Generated by Django 4.1 on 2022-11-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0012_user_story_estimacion_user_story_idsprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_story',
            name='estimacion',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
