# Generated by Django 3.2.12 on 2022-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0014_miembro_horasdisponibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
