# Generated by Django 4.1.3 on 2022-12-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0016_alter_tipous_estado_alter_user_story_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='Htrabajadas',
            field=models.IntegerField(default=0),
        ),
    ]
