# Generated by Django 4.1.3 on 2022-12-07 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyect_Agile', '0016_alter_tipous_estado_alter_user_story_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser_Story',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estimacion', models.FloatField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='N', max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('comentarios', models.TextField()),
                ('historial', models.TextField(blank=True)),
                ('UP', models.IntegerField(blank=True, null=True)),
                ('BV', models.IntegerField(blank=True, null=True)),
                ('prioridad', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idSprint', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Proyect_Agile.sprint')),
                ('idproyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Proyect_Agile.proyecto')),
                ('miembroEncargado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Proyect_Agile.miembro')),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Proyect_Agile.tipous')),
            ],
            options={
                'verbose_name': 'historical user_ story',
                'verbose_name_plural': 'historical user_ storys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
