# Generated by Django 4.1 on 2022-12-06 03:05

import Proyect_Agile.utilidades
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0016_alter_tipous_estado_alter_user_story_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_story',
            name='prioridad',
            field=models.FloatField(blank=True, null=True, validators=[Proyect_Agile.utilidades.validarDecimal]),
        ),
    ]
