# Generated by Django 4.1.3 on 2022-12-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0017_historicaluser_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipous',
            name='estado',
            field=models.TextField(default='Por hacer, En Proceso, Hecho'),
        ),
    ]
