# Generated by Django 4.1.3 on 2022-12-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0018_alter_tipous_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
