# Generated by Django 4.1.3 on 2022-12-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyect_Agile', '0017_sprint_htrabajadas'),
        ('Proyect_Agile', '0019_sprint_duracion'),
    ]

    operations = [
    ]
